### ISSUE TITLE
[SEVERE] Exception in thread "pool-1-thread-2"

### ISSUE THREAD

**Issue by JohOply** [Hidendra/LWC#537]
1.4.7R1.0
4.3.2 beta
Using Mysql

>23:16:00 [INFO] [LWC] [LWC] The updater ran into a minor issue: Connection reset
>23:16:00 [INFO] [LWC] [LWC] This can probably be ignored.
>23:16:00 [SEVERE] Exception in thread "pool-1-thread-2"
>23:16:00 [SEVERE] org.apache.commons.lang.UnhandledException: Plugin LWC v4.3.1 (b820-git-MANUAL) (February 02, 2013) generated an exception while executing task 3
at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.NullPointerException
at com.griefcraft.util.Updater$1.run(Updater.java:81)
at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftTask.run(CraftTask.java:53)
at org.bukkit.craftbukkit.v1_4_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 3 more

**Comment by JohOply** [comment]
Probably fixed with LWC Entity Locking
