### ISSUE TITLE
 java.sql.SQLException

### ISSUE THREAD

**Issue by mibby** [Hidendra/LWC#752]
LWC dev build 903.

```
2013-11-12 14:26:11 [SEVERE] java.sql.SQLException: Streaming result set com.mysql.jdbc.RowDataDynamic@131d5581 is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ensure that you have called .close() on any active streaming result sets before attempting more queries.
2013-11-12 14:26:11 [SEVERE]    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934)
2013-11-12 14:26:11 [SEVERE]    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
2013-11-12 14:26:11 [SEVERE]    at com.mysql.jdbc.MysqlIO.checkForOutstandingStreamingData(MysqlIO.java:2724)
2013-11-12 14:26:11 [SEVERE]    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1895)
2013-11-12 14:26:11 [SEVERE]    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
2013-11-12 14:26:11 [SEVERE]    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
2013-11-12 14:26:11 [SEVERE]    at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:5022)
2013-11-12 14:26:11 [SEVERE]    at com.griefcraft.sql.Database.setAutoCommit(Database.java:178)
2013-11-12 14:26:11 [SEVERE]    at com.griefcraft.util.DatabaseThread.flushDatabase(DatabaseThread.java:138)
2013-11-12 14:26:11 [SEVERE]    at com.griefcraft.util.DatabaseThread.run(DatabaseThread.java:177)
2013-11-12 14:26:11 [SEVERE]    at java.lang.Thread.run(Unknown Source)
2013-11-12 14:26:11 [SEVERE] Exception in thread "Thread-15" 
2013-11-12 14:26:11 [SEVERE] com.griefcraft.scripting.ModuleException: java.sql.SQLException: Streaming result set com.mysql.jdbc.RowDataDynamic@131d5581 is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ensure that you have called .close() on any active streaming result sets before attempting more queries.
2013-11-12 14:26:11 [SEVERE]    at com.griefcraft.sql.Database.printException(Database.java:199)
2013-11-12 14:26:11 [SEVERE]    at com.griefcraft.sql.PhysDB.saveProtection(PhysDB.java:1675)
2013-11-12 14:26:11 [SEVERE]    at com.griefcraft.model.Protection.saveNow(Protection.java:788)
2013-11-12 14:26:11 [SEVERE]    at com.griefcraft.util.DatabaseThread.flushDatabase(DatabaseThread.java:146)
2013-11-12 14:26:11 [SEVERE]    at com.griefcraft.util.DatabaseThread.run(DatabaseThread.java:177)
2013-11-12 14:26:11 [SEVERE]    at java.lang.Thread.run(Unknown Source)
2013-11-12 14:26:11 [SEVERE] Caused by: java.sql.SQLException: Streaming result set com.mysql.jdbc.RowDataDynamic@131d5581 is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ensure that you have called .close() on any active streaming result sets before attempting more queries.
2013-11-12 14:26:11 [SEVERE]    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934)
2013-11-12 14:26:11 [SEVERE]    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
2013-11-12 14:26:11 [SEVERE]    at com.mysql.jdbc.MysqlIO.checkForOutstandingStreamingData(MysqlIO.java:2724)
2013-11-12 14:26:11 [SEVERE]    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1895)
2013-11-12 14:26:11 [SEVERE]    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
2013-11-12 14:26:11 [SEVERE]    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
2013-11-12 14:26:11 [SEVERE]    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
2013-11-12 14:26:11 [SEVERE]    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
2013-11-12 14:26:11 [SEVERE]    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
2013-11-12 14:26:11 [SEVERE]    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
2013-11-12 14:26:11 [SEVERE]    at com.griefcraft.sql.PhysDB.saveProtection(PhysDB.java:1673)
2013-11-12 14:26:11 [SEVERE]    ... 4 more
```

**Comment by TheChampTF** [comment]
Can confirm this is still happening.
