### ISSUE TITLE
Economy module exception when using discounts

### ISSUE THREAD

**Issue by ezeiger92** [Hidendra/LWC#909]
When using discounts, LWC fails to find any previous locks. Instead it throws this exception and always applies the discount. Tested CraftConomy and iConomy.

Stackdump:
[20:59:22 WARN]: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 4.5.0
[20:59:22 WARN]:        at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:358)
[20:59:22 WARN]:        at com.griefcraft.listeners.LWCBlockListener.onBlockPlaceMonitor(LWCBlockListener.java:471)
[20:59:22 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:59:22 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20:59:22 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:59:22 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[20:59:22 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
[20:59:22 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[20:59:22 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[20:59:22 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[20:59:22 WARN]:        at org.bukkit.craftbukkit.v1_8_R2.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:125)
[20:59:22 WARN]:        at net.minecraft.server.v1_8_R2.ItemStack.placeItem(ItemStack.java:156)
[20:59:22 WARN]:        at net.minecraft.server.v1_8_R2.PlayerInteractManager.interact(PlayerInteractManager.java:503)
[20:59:22 WARN]:        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:734)
[20:59:22 WARN]:        at net.minecraft.server.v1_8_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52)
[20:59:22 WARN]:        at net.minecraft.server.v1_8_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
[20:59:22 WARN]:        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[20:59:22 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[20:59:22 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[20:59:22 WARN]:        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
[20:59:22 WARN]:        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710)
[20:59:22 WARN]:        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
[20:59:22 WARN]:        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
[20:59:22 WARN]:        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
[20:59:22 WARN]:        at java.lang.Thread.run(Unknown Source)
[20:59:22 WARN]: Caused by: java.lang.NullPointerException
[20:59:22 WARN]:        at com.griefcraft.lwc.EconomyModule.resolveValue(EconomyModule.java:546)
[20:59:22 WARN]:        at com.griefcraft.lwc.EconomyModule.onPostRegistration(EconomyModule.java:268)
[20:59:22 WARN]:        at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:350)
[20:59:22 WARN]:        ... 24 more

**Comment by batkins62** [comment]
also receiving issue, im using version LWC 4.5.0-SNAPSHOT (#938)(LWC-Economy Build #938)
http://pastebin.com/mY5fg6CX

**Comment by ezeiger92** [comment]
There were actually 2 issues here, I can't quite remember them, but I fixed it in a local build for my server. I'll make a fork with the changes.

**Comment by batkins62** [comment]
That would be great, or send me your jar and i will take the time to
calculate the differences

**Comment by ezeiger92** [comment]
Fork:  https://github.com/ezeiger92/LWC

Should all be working, let me know if it has issues

**Comment by batkins62** [comment]
thank you, it works just fine, i submitted that pull request

**Comment by batkins62** [comment]
Thank you works just fine
