### ISSUE TITLE
Can't download the latest build

### ISSUE THREAD

**Issue by tristankhalil** [Hidendra/LWC#916]
Hello,

Whenever I try to download, it always get the following: 

Website is offline No cached version of this page is available.
Error 522 - Connection Timed Out

Can you please fix the download link? Thank you

**Comment by am-webdev** [comment]
I ran into the same issue while starting the bukkit server. You have an unhanded exception in your code:

```
[16:38:48] [pool-3-thread-4/INFO]: [LWC] [LWC] The updater ran into a minor issue: Server returned HTTP response code: 522 for URL: http://update.griefcraft.com/lwc/branch/stable/LATEST
[16:38:48] [pool-3-thread-4/INFO]: [LWC] [LWC] This can probably be ignored.
[16:38:48] [pool-3-thread-4/WARN]: Exception in thread "pool-3-thread-4"
[16:38:48] [pool-3-thread-4/WARN]: org.apache.commons.lang.UnhandledException: Plugin LWC v4.4.0 (b881) (July 11, 2013) generated an exception while executing task 8
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.griefcraft.util.Updater$1.run(Updater.java:81)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
```

Can you verify this will be cached later on or is this plugin out of service?

**Comment by xknat** [comment]
i got the manual links here: 
[link to dev builds](http://google.com)     and [link to Release (stable)!](http://dev.bukkit.org/bukkit-plugins/lwc/files/)

**Comment by Zivci** [comment]
Webserver at ci.griefcraft.com is down, returning 522: connection timed out.
