### ISSUE TITLE
Support 1.9

### ISSUE THREAD

**Issue by HeroCC** [Hidendra/LWC#933]
Right now LWC crashes when trying to use Spigot 1.9, is there a plan for LWC to be updated to support 1.9?

**Comment by tmad40blue** [comment]
@HeroCC @Hidendra 

Further info - this is related to getOnlinePlayers() now being a deprecated method. Stacktrace:

```
[09:35:43] [Craft Scheduler Thread - 41/WARN]: Exception in thread "Craft Scheduler Thread - 41"                                                                                                                                                                                                                              
[09:35:43] [Craft Scheduler Thread - 41/WARN]: org.apache.commons.lang.UnhandledException: Plugin LWC v4.5.0-SNAPSHOT generated an exception while executing task 7                                                                                                                                                           
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)                                                                                                                                                                                                                                
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)                                                                                                                                                                                                                                    
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)                                                                                                                                                                                                                                    
        at java.lang.Thread.run(Thread.java:745)                                                                                                                                                                                                                                                                              
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;                                                                                                                                                                                                                       
        at org.mcstats.Metrics.postPlugin(Metrics.java:335)                                                                                                                                                                                                                                                                   
        at org.mcstats.Metrics.access$400(Metrics.java:57)                                                                                                                                                                                                                                                                    
        at org.mcstats.Metrics$1.run(Metrics.java:223)                                                                                                                                                                                                                                                                        
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)                                                                                                                                                                                                                                          
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)                                                                                                                                                                                                                                
        ... 3 more                                                                                                                                                                                                                                                                                                           
```

May be possible to temporarily fix with the method outlined [here](https://www.spigotmc.org/threads/minecraft-1-9-release.127186/) related to SpecialSource. Haven't tested it myself.

**Comment by HeroCC** [comment]
It looks like metrics is luckily the only issue. I fixed it for another plugin where metrics was the issue, so I may be able to fix it for LWC as well.

**Comment by Hidendra** [comment]
I will push an update in a bit after I get home.

Tyler

**Comment by tmad40blue** [comment]
Thank you so much!

**Comment by Hidendra** [comment]
What build of Spigot 1.9 are you using? I am unable to reproduce this using `git-Spigot-7d15d07-c194444 (MC: 1.9) (Implementing API version 1.9-SNAPSHOT)`

Metrics seems to post without error:

    [16:27:26 INFO]: Done (3.466s)! For help, type "help" or "?"
    [16:27:26 INFO]: [Metrics] Prepared request for LWC uncompressed=578 compressed=323

Everything seems to be working OK here. I believe I have the latest build of Spigot. If you can guide me to how to get a build that breaks, I can better look.

> "this is related to getOnlinePlayers() now being a deprecated method"

I'm not so sure. `Player[] getOnlinePlayers()` is deprecated, but `Collection<? extends Player> getOnlinePlayers()` is not [[1]](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Server.html#getOnlinePlayers()) which is what MCStats (what is erroring above) should use.

**Comment by Hidendra** [comment]
I just had a friend asking me about a different plugin that was breaking with the same error (`java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()`). He said he downloaded Spigot 1.9 last night. I downloaded it 10 minutes ago (so it's pretty new and we are at different commits of Spigot). So he is updating it now and I'm waiting to hear back if updating it fixed it for him.

So could you try making sure your Spigot is up to date? :fearful:

**Comment by tmad40blue** [comment]
Yep, md_5 has been pushing A LOT of Spigot updates today. I'm pretty sure one of them must have fixed the issue. I'm re-running BuildTools and getting the latest commits now, will see what happens.

LWC version is build 938 from http://ci.griefcraft.com/job/LWC/ , BTW.

**Comment by HeroCC** [comment]
Just reran buildtools, same thing.

Error: http://imgur.com/uERziaS

Version: http://imgur.com/YEoQ9av

**Comment by tmad40blue** [comment]
Confirmed, getting same error as HeroCC with latest Spigot built using BuildTools 5 minutes ago.

**Comment by Hidendra** [comment]
@HeroCC Are you using build 938, same as @tmad40blue ?

I'm trying to figure out how your MCStats class is calling the wrong method, when in the LWC jar it's using the right one. Perhaps it's a classloader issue and it's using the MCStats class from an older plugin that hasn't updated it.

I will make a change to put the MCStats class into a package unique to LWC.

**Comment by HeroCC** [comment]
Yep, latest from jenkins.

**Comment by Hidendra** [comment]
Okay, give [build 939](http://ci.griefcraft.com/job/LWC/939/) a shot. It's possible you'll get the same error but from a different plugin now.

**Comment by HeroCC** [comment]
That fixed it! Thanks! While you are at it, mind checking out a few other Pull Requests? (In particular #881 #902, but there are a few others). Thanks for the great plugin and fast updates!

**Comment by Hidendra** [comment]
@HeroCC Yeah, taking a peek now
