### ISSUE TITLE
NPE when using "lwc admin version"

### ISSUE THREAD

**Issue by tmad40blue** [Hidendra/LWC#934]
Hi, getting this whenever I attempt to use `/lwc admin version` in-game or through my server console. Latest Spigot (for now...) and LWC build 939 from your Jenkins.

```
[16:31:07 INFO]: tmad40blue issued server command: /cadmin version
[16:31:07 INFO]: [LWC] [LWC] The updater ran into a minor issue: http://update.griefcraft.com/lwc/branch/stable/LATEST
[16:31:07 INFO]: [LWC] [LWC] This can probably be ignored.
[16:31:07 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cadmin' in plugin LWC v4.5.0-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-1a196e1-76c0425]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-1a196e1-76c0425]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot.jar:git-Spigot-1a196e1-76c0425]
        at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1302) [spigot.jar:git-Spigot-1a196e1-76c0425]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1137) [spigot.jar:git-Spigot-1a196e1-76c0425]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-1a196e1-76c0425]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-1a196e1-76c0425]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-1a196e1-76c0425]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-1a196e1-76c0425]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot.jar:git-Spigot-1a196e1-76c0425]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-1a196e1-76c0425]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-1a196e1-76c0425]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-1a196e1-76c0425]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 4.5.0
        at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:358) ~[?:?]
        at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:155) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-1a196e1-76c0425]
        ... 15 more
Caused by: java.lang.NullPointerException
        at com.griefcraft.modules.admin.AdminVersion.onCommand(AdminVersion.java:69) ~[?:?]
        at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:340) ~[?:?]
        at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:155) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-1a196e1-76c0425]
        ... 15 more
```

**Comment by theyapps** [comment]
Caused by update site being down. Added a quick fix to https://github.com/theyapps/LWC/commit/20071a637033efd43cd7436e643bdc596a1691dc
