### ISSUE TITLE
jenkins

### ISSUE THREAD

**Issue by EpicRhox** [Hidendra/LWC#948]
I keep getting error 520 when trying to download the 941 build from jenkins

My console keeps giving me this error and was hoping that downloading the 941 build would fix it. LWC is everying I want from a protection plugin and don't want to even think about having to use a different one. Thank you.

ERROR Could not pass event BlockRedstoneEvent to LWC v4.4.0 (b881) (July 11, 2013)
21.07 13:55:15 [Server] INFO org.bukkit.event.EventException
21.07 13:55:15 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-latest.jar:git-Spigot-078e2f8-7f9fbe5]
21.07 13:55:15 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-latest.jar:git-Spigot-078e2f8-7f9fbe5]
21.07 13:55:15 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-latest.jar:git-Spigot-078e2f8-7f9fbe5]
21.07 13:55:15 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-latest.jar:git-Spigot-078e2f8-7f9fbe5]
21.07 13:55:15 [Server] INFO at net.minecraft.server.v1_10_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:106) [spigot-latest.jar:git-Spigot-078e2f8-7f9fbe5]
21.07 13:55:15 [Server] INFO at net.minecraft.server.v1_10_R1.BlockPressurePlateAbstract.b(BlockPressurePlateAbstract.java:78) [spigot-latest.jar:git-Spigot-078e2f8-7f9fbe5]
21.07 13:55:15 [Server] INFO at net.minecraft.server.v1_10_R1.WorldServer.a(WorldServer.java:737) [spigot-latest.jar:git-Spigot-078e2f8-7f9fbe5]
21.07 13:55:28 [Multicraft] Skipped 62 lines due to rate limit (100/s)

**Comment by xknat** [comment]
outdated use a unoffical build (google)
